version: "3.9"
services:
     deconz:
          image: deconzcommunity/deconz
          container_name: deconz
          restart: always
          ports:
               - "80:80"
               - "443:443"
          volumes:
               - /opt/deconz:/opt/deCONZ
          devices:
               - /dev/ttyACM0 # Conbee II = /dev/ttyACM0, RaspBee = /dev/ttyAMA0 or /dev/ttyS0
          environment:
               - DECONZ_WEB_PORT=80
               - DECONZ_WS_PORT=443
               - DEBUG_INFO=1
               - DEBUG_APS=0
               - DEBUG_ZCL=0
               - DEBUG_ZDP=0
               - DEBUG_OTAU=0
     mosquitto:
          image: eclipse-mosquitto
          container_name: mosquitto
          restart: unless-stopped
          ports:
               - "1883:1883"
               - "1884:1884"
               - "9001:9001"
          volumes:
               - ./mosquitto/config:/mosquitto/config
               - ./mosquitto/data:/mosquitto/data
               - ./mosquitto/log:/mosquitto/log
     nodered:
          image: nodered/node-red
          container_name: nodered
          depends_on:
               - deconz
               - mosquitto
          ports:
               - "1880:1880"
          volumes:
               - ./nodered/data:/data
     openhab:
          image: openhab/openhab:3.1.0
          container_name: openhab
          restart: always
          #network_mode: host
          ports:
               - "8080:8080"
               - "8443:8443"
          volumes:
               - /etc/localtime:/etc/localtime:ro
               - /etc/timezone:/etc/timezone:ro
               - /opt/openhab/addons:/openhab/addons
               - /opt/openhab/conf:/openhab/conf
               - /opt/openhab/userdata:/openhab/userdata
          environment:
               - OPENHAB_HTTP_PORT=8080
               - OPENHAB_HTTPS_PORT=8443
               - EXTRA_JAVA_OPTS=-Duser.timezone=Europe/Berlin
          devices:
               - /dev/ttyACM0
     homeassistant:
          container_name: homeassistant
          image: "ghcr.io/home-assistant/home-assistant:stable"
          volumes:
               - /opt/homeassistant/config:/config
               - /etc/localtime:/etc/localtime:ro
          restart: unless-stopped
          privileged: true
          network_mode: host
          devices:
               - /dev/ttyACM0
     portainer:
          image: portainer/portainer-ce
          container_name: portainer
          restart: unless-stopped
          ports:
               - "9000:9000"
          volumes:
               - "/var/run/docker.sock:/var/run/docker.sock"
               - "./portainer/data:/data"
